apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searcher
  annotations:
    backstage.io/kubernetes-id: "k8s-read"
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=k8s-read'
    argocd/app-name: "k8s-read"

  description: Searcher
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
