apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shuffle-api
  annotations:
      backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=elasticsearch'
  description: Shuffle API
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
